# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aitutor < Formula
  desc "Interactive terminal tutorial for AI coding concepts"
  homepage "https://github.com/naorpeled/aitutor"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/naorpeled/aitutor/releases/download/v0.1.0/aitutor_0.1.0_darwin_amd64.tar.gz"
      sha256 "dab86b7c7612496d8d3ad3ef6e3dfe26eea790cc33cea84d2e0da1625725be39"

      define_method(:install) do
        bin.install "aitutor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/naorpeled/aitutor/releases/download/v0.1.0/aitutor_0.1.0_darwin_arm64.tar.gz"
      sha256 "67cffb03c164449d7e1c44cd71a2cde46cf0d8cc83a0d04b6b04f2a0a455d0a2"

      define_method(:install) do
        bin.install "aitutor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/naorpeled/aitutor/releases/download/v0.1.0/aitutor_0.1.0_linux_amd64.tar.gz"
      sha256 "74de92194c1907e74bb3b686f07d8402d327bc71f62257b84c37c2fa1fea8c18"
      define_method(:install) do
        bin.install "aitutor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/naorpeled/aitutor/releases/download/v0.1.0/aitutor_0.1.0_linux_arm64.tar.gz"
      sha256 "9303542081e8a262f6bc9a8fe56c07e5e4dd2cc1318253467eca406f0d22932e"
      define_method(:install) do
        bin.install "aitutor"
      end
    end
  end
end
