# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aitutor < Formula
  desc "Interactive terminal tutorial for AI coding concepts"
  homepage "https://github.com/naorpeled/aitutor"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/naorpeled/aitutor/releases/download/v0.1.6/aitutor_darwin_amd64.tar.gz"
      sha256 "eed73a156352a128e1aa77a0062209dcd0312a964862eda0ab480a5ff04994dc"

      define_method(:install) do
        bin.install "aitutor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/naorpeled/aitutor/releases/download/v0.1.6/aitutor_darwin_arm64.tar.gz"
      sha256 "133aa5b54116f5edb67b445879368bba183642de35c4081103869710b4a71ff5"

      define_method(:install) do
        bin.install "aitutor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/naorpeled/aitutor/releases/download/v0.1.6/aitutor_linux_amd64.tar.gz"
      sha256 "fee5ba712e8a2b9ad3c818d0efb7c3838a11a6a5c7ee023780dcb8ee82b8d846"
      define_method(:install) do
        bin.install "aitutor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/naorpeled/aitutor/releases/download/v0.1.6/aitutor_linux_arm64.tar.gz"
      sha256 "7f7bdc1eb50dda159102231e91b7cd561a22451800fb08dfbb2e18da4b0b7fec"
      define_method(:install) do
        bin.install "aitutor"
      end
    end
  end
end
